### ISSUE TITLE
Background trigger for web

### ISSUE THREAD

**Issue by peggyrayzis** [jamesreggio/apollo-cache-persist#1]
We can use the [page visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to trigger background persistence on web when the tab is minimized 🎉

**Comment by jamesreggio** [comment]
Yep! Considered that, but I excluded it because it encourages data loss.

On React Native, in nearly all scenarios, an app will transition to the
background before it terminates, and usually remains in the background
state for several seconds before termination, giving it opportunity to
persist. (This is even true if the user manually terminates the app via the
app switcher, because the app transitions to the 'inactive' state and
persists as soon as the app switcher is activated. As long as the user
isn't super fast — or the phone, super slow — persistence generally
completes before the app is swiped and closed.) The only case where
background persistence is likely to lose data in RN is if the app crashes,
but if your app is crashing, you have other reasons to fix it.

The web is a different beast. On the web, it is typical for users to close
a tab without first transitioning that tab to the background. I thought to
handle this edge case by hooking onbeforeunload, however the async nature
of the persistence means that it is likely not to complete before the tab's
VM is halted.

I don't view this as a huge loss for the web, because performance was my
motivation for background persistence on RN. In an ideal world, we'd
persist instantly after every write, but persisting blocks the UI thread on
RN and can do so for several hundred milliseconds. The web is generally
much faster here (it can JIT, and marshalling the serialized store doesn't
block the UI), so I think it's safe and reasonable to only offer the write
trigger with a configurable debounce interval.


On Dec 4, 2017 9:12 AM, "Peggy Rayzis" <notifications@github.com> wrote:

We can use the page visibility API
<https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API> to
trigger background persistence on web when the tab is minimized 🎉

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jamesreggio/apollo-cache-persist/issues/1>, or mute the
thread

**Comment by peggyrayzis** [comment]
Your reasoning makes sense to me! I'm down to hold off on this unless enough people request it, but it seems like it won't be needed.
